fix env

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -73,21 +73,18 @@ jobs:
         uses: bahmutov/npm-install@v1
 
       - name: 🏄 Copy test env vars
-        run: cp .env.example .env
+        run: |
+          set -e # exit on error
+          cp .env.example .env
+          cat .env >> $GITHUB_ENV
 
       - name: 🖼 Build icons
         run: npm run build:icons
-
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
-        with:
-          limit-access-to-actor: true
 
       - name: 🛠 Setup Database
         run: |
           set -e # exit on error
           npx tsx migrate.ts
-          sqlite3 data/data.db ".schema"
           npx tsx seed.ts
 
       - name: ⚡ Run vitest
@@ -102,7 +99,10 @@ jobs:
         uses: actions/checkout@v3
 
       - name: 🏄 Copy test env vars
-        run: cp .env.example .env
+        run: |
+          set -e # exit on error
+          cp .env.example .env
+          cat .env >> $GITHUB_ENV
 
       - name: ⎔ Setup node
         uses: actions/setup-node@v3
